apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{include "app.fullname" .}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:  
  - host: {{.Release.Name}}.local.medrio.com
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
          name: {{include "app.fullname" .}}
          port:
            number: {{ .Values.service.port}}
  