apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "app.fullname" .}}
  template:
    metadata:
      labels:
        app: {{include "app.fullname" .}}
    spec:
      containers:
      - name: {{include "app.fullname" .}}-{{.Release.Revision}}
        image: {{ .Values.image.repository }}
        imagePullPolicy: Never 
        args: []
        env:
        - name : ASPNETCORE_URLS
          value: "http://+:4299"    
        ports:
        - containerPort: 4299
