apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{include "app.fullname" .}}
  name: {{include "app.fullname" .}}
spec:
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port}}
      targetPort: 4299
  selector:
    app: {{include "app.fullname" .}}
