services:
  chainofproxycall1:
    container_name: chainofproxycall1
    image: chain-of-proxy-call:latest
    # build: 
    #   context: .
    #   dockerfile: ChainOfProxyCall/Dockerfile
    ports:
      - "5301:8080"
  chainofproxycall2:
    container_name: chainofproxycall2
    image: chain-of-proxy-call:latest
    ports:
      - "5302:8080"
  chainofproxycall3:
    container_name: chainofproxycall3
    image: chain-of-proxy-call:latest
    ports:
      - "5303:8080"
