
services:
  chainofproxycall:
    build:
      context: .
      dockerfile: ChainOfProxyCall/Dockerfile
    ports:
      - "8080"  #   "host:container".  Here means only container port 8080 is specified. Host port will be randomly assigned. 
    deploy:     # Swarm mode
      replicas: 3
      restart_policy:
        condition: on-failure
