apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapinet5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapinet5 
  template:
    metadata:
      labels:
        app: webapinet5
    spec:
      containers:
      - name: webapinet5-1
        image: webapinet5publish
        imagePullPolicy: Never 
        args: []
        env:
        - name : ASPNETCORE_URLS
          value: "http://+:4299"    
        ports:
        - containerPort: 4299
