apiVersion: v1
kind: Pod
metadata:
  name: webapinet5pod
spec:
  containers:
  - name: webapinet5-1
    image: webapinet5publish
    imagePullPolicy: Never 
    args: []
    env:
    - name : ASPNETCORE_URLS
      value: "http://+:851"    
    ports:
    - containerPort: 851
  - name: webapinet5-2
    image: webapinet5publish
    imagePullPolicy: Never 
    args: []
    env:
    - name : ASPNETCORE_URLS
      value: "http://+:852"
    ports:
    - containerPort: 852