version: '3.8'

services:
  ryan.webapinet5published:
    image: webapinet5publish
    container_name: WebApiNet5BackEnd
    build:
      target: final
      labels:
        label1: "RyanSingleStageLocally" # Ryan: this label will in both image and container at different paths, but no functional use except debug
      context: ../_Publish
      dockerfile: ./DockerfilePublish #relative path in context
      # args:
      #  version: "1.0.0.100"    # this can be passed in docker file, not in use here    
    restart: unless-stopped
    ports:
      - "12888:80"
      - "252:443"
    environment: 
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_URLS: "https://+:443;http://+:80"
        ASPNETCORE_HTTPS_PORT: "443"
        ASPNETCORE_Kestrel__Certificates__Default__Password: medrio123!
        ASPNETCORE_Kestrel__Certificates__Default__Path: Certs/localhost-openssl.pfx
